general:
  basepath_windows: C:/Users/ga25mal/
  basepath_macos: /Users/fnoic/
  project_path: PycharmProjects/reconstruct/

segmentation:
  cloud_path: /data/in_test/test_junction_snip.txt
  # path to raw cloud
  #  cloud_path: /data/in_instances/beams.txt

local:
  normals_radius: 0.05
  max_nn: 30
  max_dist_cross: 0.4
  max_dist_to_plane: 0.05
  supernormal_radius: 0.20

initial:
  rnd_pick_ratio: 0.05

clustering:
  max_dist_euc: 0.2  # re-think with cross and to-plane limits
  dist_thresh_normal: 0.1
  angle_thresh_normal: 30
  dist_thresh_supernormal: 0.5
  angle_thresh_supernormal: 12
  dist_thresh_ransac: 0.0075
  count_thresh_ransac: 1000
  iter_thresh_ransac: 100000000
  count_thresh_ransac_rest: 50
  dist_thresh_dbscan: 0.04
  count_thresh_dbscan: 10

