project:
  # os dependent paths are hardcoded
  basepath_windows: C:/Users/ga25mal/
  basepath_macos: /Users/fnoic/
  project_path: PycharmProjects/reconstruct/
  parking_path: data/parking/

segmentation:
  cloud_path: /data/in_test/test_junction_snip.txt
  # path to raw cloud
  #  cloud_path: /data/in_instances/beams.txt

local_features:
  normals_radius: 0.05
  max_nn: 30
  max_dist_cross: 0.4
  max_dist_to_plane: 0.05
  supernormal_radius: 0.15
  neighbor_shape: oriented_ellipsoid
  supernormal_cube_dist: 0.15
  supernormal_ellipsoid_a: 0.15
  supernormal_ellipsoid_bc: 0.075

initial:
  rnd_pick_ratio: 0.05

clustering:
  max_dist_euc: 0.2  # re-think with cross and to-plane limits
  max_ransac_iterations: 1000
  dist_thresh_normal: 0.1
  angle_thresh_normal: 30
  dist_thresh_supernormal: 0.5
  angle_thresh_supernormal: 20
  dist_thresh_ransac: 0.0075
  count_thresh_ransac: 1000
  iter_thresh_ransac: 100000000
  count_thresh_ransac_rest: 50
  dist_thresh_dbscan: 0.03
  count_thresh_dbscan: 10
  dist_thresh_ball: 0.12
  ransac_n: 3
  ransac_dist_thresh: 0.01
  ransac_iterations: 100000000
  ransac_min_count: 1000
  ransac_rest_thresh: 50
  ransac_blanks: 100
  dbscan_eps_dist: 0.03
  dbscan_min_count: 10

region_growing:
  supernormal_angle_deviation: 10

