project:
  basepath_windows: C:/Users/ga25mal/
  basepath_macos: /Users/fnoic/
  project_path: PycharmProjects/reconstruct/
  parking_path: data/parking/
  experiment_path: data/experiment/

data:
  cloud_path: /data/experiment/initial_2.txt
  orientation_path: /data/in_full/orientation_list.yaml

preprocess:
  downsample_flag: False
  voxel_size: 0.01
  normals_radius: 0.05
  normals_max_nn: 30

planar_patch:
  ransac_blank_ok: 100
  ransac_distance_threshold: 0.005
  ransac_ransac_n: 3
  ransac_num_iterations: 100000000
  dbscan_eps: 0.03
  dbscan_min_samples: 10

local_neighborhood:
  shape: sphere
  radius_a: 0.1
  context_radius: 0.05

supernormal:
  radius: 0.35
  input: no ransac

region_growing:
  min_patch_size: 100
  neighborhood_shape: sphere
  neighborhood_radius: 0.3
  leftover_relative: 0.02
  supernormal_angle_deviation_patch: 15
  ransacnormal_angle_deviation_patch: 10
  supernormal_angle_deviation_point: 10

skeleton:
  init_min_count: 20
  init_max_angle_rn_sn: 10
  init_max_angle_n_sn: 15
  allocate_max_dist_patch: 0.15
  allocate_max_dist_point: 0.05
  ransac_method: open3d
  ransac_distance_threshold: 0.0005
  ransac_num_iterations: 50000
  ransac_ransac_n: 3
  aggregate_distance_max: 0.4
  aggregate_angle_max: 30

skeleton_visual:
  line_length_projection: 0.2

cs_fit:
  method: nsga3
  grid_size: 0.01
  n_downsample: 200
  n_pop: 100
  n_lambda: 100
  n_mu: 100
  n_gen: 50
  inlier_thresh: 0.005
  ifc_cs_path: /Users/fnoic/PycharmProjects/IfcOpenShell/src/bonsai/bonsai/bim/data/libraries/IFC4 EU Steel.ifc
